/// <reference path="node_modules/@citizenfx/client/index.d.ts"/>
/// <reference path="node_modules/@citizenfx/server/index.d.ts"/>

/*
	Shared rescue specific variables and functions
*/

/**
 * Improvised Enum of available types of rescues
 */
const RESCUE_TYPE =
{
	NONE: "NONE",
	GROUND: "GROUND",
	AIR: "AIR"
};

/**
 * Improvided Enum of rescue status
 */
const RESCUE_STATUS =
{
	FAILED: "FAILED",
	ONGOING: "ONGOING",
	COMPLETE: "COMPLETE"
};

/**
 * Improvided Enum of rescue stages
 */
const RESCUE_STAGE =
{
	GET_TYPE: "GET_TYPE",
	GET_POINTS: "GET_POINTS",
	PED_CREATE: "PED_CREATE",
	PED_DELETE: "PED_DELETE",
	PED_GOTO_POINT: "PED_GOTO_POINT",
	PED_ENTER_VEHICLE: "PED_ENTER_VEHICLE",
	PED_EXIT_VEHICLE: "PED_EXIT_VEHICLE",
	PED_RAPPEL_VEHICLE: "PED_RAPPEL_VEHICLE",
	PED_ATTACH_OBJECT: "PED_ATTACH_OBJECT",
	PED_DETACH_OBJECT: "PED_DETACH_OBJECT",
	VEHICLE_CREATE: "VEHICLE_CREATE",
	VEHICLE_DELETE: "VEHICLE_DELETE",
	VEHICLE_GOTO_POINT: "VEHICLE_GOTO_POINT",
	VEHICLE_ATTACH_OBJECT: "VEHICLE_ATTACH_OBJECT",
	VEHICLE_DETACH_OBJECT: "VEHICLE_DETACH_OBJECT",
	OBJECT_CREATE: "OBJECT_CREATE",
	OBJECT_DELETE: "OBJECT_DELETE",
	OBJECT_ATTACH_PLAYER: "OBJECT_ATTACH_PLAYER",
	OBJECT_DETACH_PLAYER: "OBJECT_DETACH_PLAYER",
	PLAYER_TELEPORT: "PLAYER_TELEPORT"
};

/**
 * List of rescue stages in order of execution
 */
const RESCUE_ORDER = 
[
	RESCUE_STAGE.GET_TYPE,
	RESCUE_STAGE.GET_POINTS,
	RESCUE_STAGE.VEHICLE_CREATE,
	RESCUE_STAGE.PED_CREATE,
	RESCUE_STAGE.VEHICLE_GOTO_POINT,
	RESCUE_STAGE.PED_EXIT_VEHICLE,
	RESCUE_STAGE.OBJECT_CREATE,
	RESCUE_STAGE.PED_ATTACH_OBJECT,
	RESCUE_STAGE.PED_GOTO_POINT,
	RESCUE_STAGE.PED_DETACH_OBJECT,
	RESCUE_STAGE.OBJECT_ATTACH_PLAYER,
	RESCUE_STAGE.PED_ATTACH_OBJECT,
	RESCUE_STAGE.PED_GOTO_POINT,
	RESCUE_STAGE.PED_DETACH_OBJECT,
	RESCUE_STAGE.VEHICLE_ATTACH_OBJECT,
	RESCUE_STAGE.PED_ENTER_VEHICLE,
	RESCUE_STAGE.VEHICLE_GOTO_POINT,
	RESCUE_STAGE.OBJECT_DETACH_PLAYER,
	RESCUE_STAGE.PLAYER_TELEPORT,
	RESCUE_STAGE.VEHICLE_GOTO_POINT,
	RESCUE_STAGE.VEHICLE_DETACH_OBJECT,
	RESCUE_STAGE.OBJECT_DELETE,
	RESCUE_STAGE.PED_DELETE,
	RESCUE_STAGE.VEHICLE_DELETE
];

/**
 * Contains each stage init function
 * 
 * Map of stage -> function
 * 
 * key: RESCUE_STAGE Enum
 * 
 * value: function 
 */
const RESCUE_FUNCTION_INIT = {};

/**
 * Contains each stage result function
 * 
 * Map of stage -> function
 * 
 * key: RESCUE_STAGE Enum
 * 
 * value: function 
 */
const RESCUE_FUNCTION_RESULT = {};